/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class srcjni_jni_test */

#ifndef _Included_srcjni_jni_test
#define _Included_srcjni_jni_test
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     srcjni_jni_test
 * Method:    testHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_srcjni_jni_1test_testHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
